clc;

%% build quadrature coupling 

% try to build with omp
try
    if ispc
		mex -output Assembly_SCOUPL_Lop COMPFLAGS="$COMPFLAGS /openmp" -v -O -largeArrayDims QuadCoil2Scat_ompmex.cpp Coupling.cpp;
        
    elseif ismac

         
         % build factorized coupling matrix
         
         mex -output omp_mexCoupling_Mpp COMPFLAGS='$COMPFLAGS -fopenmp' LDFLAGS='$LDFLAGS -fopenmp' CXXOPTIMFLAGS='$CXXOPTIMFLAGS -fopenmp' -v -O -largeArrayDims Coupling_Cross_mex.cpp...
             -L"../../../../c++/libs/"  ...
             -L"/opt/local/lib/"...
             -L"/opt/local/lib/gcc49"...
             -L"../../../../c++/external/lapack-3.7.0"...
             -lgfortran -ltmglib -lrefblas -llapack -lmc01utils -lmc01geo -lmc01mlaa -lmc01quads -lmc01numeric -lmc01lowrank -ldemcem -lmc01sie -lmc01vie ...
             -I"../../../../c++/include/"...
             -I"../../../../c++/external/boost_1_58_0c/";
         
    else 
        
         
       % build factorized coupling matrix
         
        mex  -output omp_mexCoupling_Mpp CXXFLAGS='$CXXFLAGS -std=c++11'  COMPFLAGS='$COMPFLAGS -fopenmp'...
            LDFLAGS='$LDFLAGS -fopenmp' CXXOPTIMFLAGS='$CXXOPTIMFLAGS -fopenmp' -v -O -largeArrayDims Coupling_Cross_mex.cpp ...
            -L"../../../../c++/libs"  ...
            -L"/opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.2/"...
            -L"../../../../c++/external/lapack-3.7.0"...
            -L"./"...
             -lgomp -lmc01sie -lmc01vie -lmc01geo -lmc01mlaa -lmc01quads -lmc01numeric -lmc01lowrank -lmc01numeric  -lgfortran -llapack -lrefblas -ltmglib -ldemcem -lgfortran  -lmc01utils...
            -I"../../../../c++/include/"...
            -I"../../../../c++/external/boost_1_58_0c/";
    end
    
catch me
    
    % use the sequential version
    fprintf(1, '\n\n\n  Warning: no openmp compatible compiler\n  Mex functions will be executed in single core\n\n');
    pause(3);

    if ismac
        mex -output mexCoupling_Mpp CXXFLAGS='$CXXFLAGS -std=c++11' -v -O -largeArrayDims Coupling_Cross_mex.cpp ...
            -L"../external/marie_libs/"  ...
            -L"/opt/local/lib/"...
            -L"../external/lapack-3.7.0"...
            -lmc01utils -lmc01geo -lmc01mlaa -lmc01quads -lmc01numeric -lmc01lowrank -ldemcem -lmc01sie -lmc01vie ... 
            -I"../../../../mri_cpp/marie/c++/include/"...
            -I"../external/boost_1_58_0c/";

    elseif isunix
        mex -output mexCoupling_Mpp CXXFLAGS='$CXXFLAGS -std=c++11'  -v -O -largeArrayDims Coupling_Cross_mex.cpp ...
        -L"../../../../c++/libs"  ...
        -L"/opt/rh/devtoolset-3/root/usr/lib/gcc/x86_64-redhat-linux/4.9.2/"...
        -L"../../../../c++/external/lapack-3.7.0"...
        -L"./"...
         -lgomp -lmc01sie -lmc01vie -lmc01geo -lmc01mlaa -lmc01quads -lmc01numeric -lmc01lowrank -lgfortran -llapack -lrefblas -ltmglib -ldemcem -lgfortran  -lmc01utils...
        -I"../../../../c++/include/"...
        -I"../../../../c++/external/boost_1_58_0c/";
    end;

end;

%% End of file
